  0%|          | 0/10000 [00:00<?, ?it/s]  0%|          | 1/10000 [00:03<10:20:54,  3.73s/it]  0%|          | 20/10000 [00:03<23:58,  6.94it/s]    0%|          | 29/10000 [00:04<18:17,  9.09it/s]  0%|          | 33/10000 [00:04<17:04,  9.73it/s]  0%|          | 36/10000 [00:04<15:46, 10.53it/s]  0%|          | 39/10000 [00:05<15:20, 10.82it/s]  0%|          | 41/10000 [00:05<17:11,  9.65it/s]  0%|          | 46/10000 [00:05<14:18, 11.60it/s]  0%|          | 48/10000 [00:05<14:15, 11.63it/s]  0%|          | 50/10000 [00:06<15:34, 10.65it/s]  1%|          | 55/10000 [00:06<13:49, 11.99it/s]  1%|          | 57/10000 [00:06<14:20, 11.55it/s]  1%|          | 61/10000 [00:06<10:56, 15.14it/s]  1%|          | 63/10000 [00:07<12:43, 13.02it/s]  1%|          | 65/10000 [00:07<13:09, 12.58it/s]  1%|          | 67/10000 [00:07<21:53,  7.56it/s]  1%|          | 69/10000 [00:08<23:18,  7.10it/s]  1%|          | 77/10000 [00:08<11:21, 14.57it/s]  1%|          | 80/10000 [00:08<10:17, 16.06it/s]  1%|          | 83/10000 [00:08<14:10, 11.66it/s]  1%|          | 88/10000 [00:09<10:46, 15.34it/s]  1%|          | 91/10000 [00:09<11:25, 14.47it/s]  1%|          | 93/10000 [00:09<13:39, 12.08it/s]  1%|          | 97/10000 [00:10<15:41, 10.52it/s]  1%|          | 99/10000 [00:10<14:45, 11.19it/s]  1%|          | 102/10000 [00:10<16:19, 10.10it/s]Process ForkPoolWorker-108:
Process ForkPoolWorker-104:
Traceback (most recent call last):
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/queues.py", line 380, in put
    self._writer.send_bytes(obj)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 430, in _send_bytes
    self._send(header + buf)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 387, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/queues.py", line 380, in put
    self._writer.send_bytes(obj)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 430, in _send_bytes
    self._send(header + buf)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 387, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-106:
Process ForkPoolWorker-113:
Process ForkPoolWorker-110:
Traceback (most recent call last):
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/queues.py", line 380, in put
    self._writer.send_bytes(obj)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 430, in _send_bytes
    self._send(header + buf)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 387, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/queues.py", line 380, in put
    self._writer.send_bytes(obj)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 430, in _send_bytes
    self._send(header + buf)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 387, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-112:
Traceback (most recent call last):
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/queues.py", line 380, in put
    self._writer.send_bytes(obj)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 430, in _send_bytes
    self._send(header + buf)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 387, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/queues.py", line 380, in put
    self._writer.send_bytes(obj)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 430, in _send_bytes
    self._send(header + buf)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 387, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
/var/spool/slurmd/job13510911/slurm_script: line 13: 3535408 Killed                  python3 main2.py $*
Traceback (most recent call last):
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/pool.py", line 131, in worker
    put((job, i, result))
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/queues.py", line 380, in put
    self._writer.send_bytes(obj)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 430, in _send_bytes
    self._send(header + buf)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 387, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/queues.py", line 380, in put
    self._writer.send_bytes(obj)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 430, in _send_bytes
    self._send(header + buf)
  File "/home4/s4279239/.local/lib/python3.11/site-packages/multiprocess/connection.py", line 387, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-114:
slurmstepd: error: Detected 1 oom_kill event in StepId=13510911.batch. Some of the step tasks have been OOM Killed.
